name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Install Ninja
      run: choco install ninja -y

    - name: Configure with CMake
      run: cmake -S . -B build -G "Ninja"

    - name: Build with CMake
      run: cmake --build build