name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update

    - name: Cache CMake Build Directory
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-cmake-build-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-cmake-build-

    - name: Remove build directory
      run: |
        if [ -d build ]; then
          rm -rf build
        fi
      shell: bash

    - name: Configure CMake
      run: cmake -S . -B build -G "Ninja"

    - name: Build
      run: cmake --build build
