name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build

    - name: Ensure clean build directory
      run: |
        if [ -d build ]; then
          rm -rf build
        fi
      shell: bash

    - name: Configure CMake
      run: cmake -S . -B build -G "Ninja"

    - name: Build
      run: cmake --build build
