name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the project file relative to the root of the project.
  PROJECT_FILE_PATH: Utils.vcxproj

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; \
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install Windows SDK
      run: choco install windows-sdk-10.0 --version=10.0.22621.0 -y

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: List Windows SDK Directory
      run: dir "$env:WindowsSdkDir"

    - name: Verify Environment Variables
      run: |
        echo "WindowsSdkDir: $env:WindowsSdkDir"
        echo "WindowsSdkVersion: $env:WindowsSdkVersion"

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:WindowsTargetPlatformVersion=10.0.22621.0 ${{env.PROJECT_FILE_PATH}}