name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FILE_PATH: Utils.vcxproj
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: List Installed Windows SDKs
      run: dir "C:\Program Files (x86)\Windows Kits\10\Lib"

    - name: Verify Environment Variables
      run: |
        echo "WindowsSdkDir: $env:WindowsSdkDir"
        echo "WindowsSdkVersion: $env:WindowsSdkVersion"

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:WindowsTargetPlatformVersion=10.0 ${{env.PROJECT_FILE_PATH}}